### ISSUE TITLE
Visual bug on the editor

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#102]
**Issue description**
At te moment the editor menu appears under the structure:

**Current behavior**
![mdrv8kin](https://cloud.githubusercontent.com/assets/1953388/24499622/3d1b7a54-153a-11e7-9f36-e73d713d7bf0.jpg)

**Expected behavior**
The menu panel on top layer of the the structure / layout

**Steps to reproduce**
Right click inside of the editor area near the separators

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.12.1-alpha / 592fc72

**Comment by qiuzhong** [comment]
Verified with [20fc049](https://github.com/01org/zephyrjs-ide/commit/20fc049b882929ecabb1a08fe97f0f65694725a9), this issue is not reproducible. The popup menu looks good now, see the screenshot:
![screenshot from 2017-04-19 19-04-17](https://cloud.githubusercontent.com/assets/11829497/25228388/dc885254-25fe-11e7-9a90-642c7b1e8aa1.png)
