### ISSUE TITLE
Adding the logo mark to the website

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#122]
**Issue description**
Adding the logo mark (attached PNG image of the mark and examples)

![landing-page](https://cloud.githubusercontent.com/assets/1953388/25624152/740d93fa-2f50-11e7-9ca6-cc340753a4b9.jpg)

![header-example](https://cloud.githubusercontent.com/assets/1953388/25624157/78491390-2f50-11e7-92b7-0671a3138409.jpg)

![logomark](https://cloud.githubusercontent.com/assets/1953388/25624164/7a20eaa8-2f50-11e7-9382-5c43cc992536.png)

**Current behavior**
Missing the logo mark

**Expected behavior**
Logo mark in the landing page and in the header of the website

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.13.2-alpha / 8050eef

**Comment by clagom** [comment]
@siovene I attached a big sized logo mark for the retina displays and high resolution monitors.
Size in the landing page: 114 x 84 px
Size in the header: 38 x 28 px
I would remove the word "Hello" from the landing page when adding the logo, changing the margins and paddings like in the attached example.

**Comment by clagom** [comment]
P.S. I see there's a misalignment now, we can fix that too:

![screen shot 2017-05-02 at 16 15 04](https://cloud.githubusercontent.com/assets/1953388/25624851/9d550f5c-2f52-11e7-84e3-ea6a115677ef.png)

**Comment by siovene** [comment]
> P.S. I see there's a misalignment now between the title/mark and the call to action buttons below

I was playing a bit with that and it's problematic. If I align it so the two menu entries are center-aligned with the app name above, then the whole thing still looks off-alignment because of the `>` symbols.

If I center-align the call-for-action bar *as a whole*, then it looks off because the text would be too much to the let.

I propose we remove the `>` symbol and either color code the words themselves, or add a colored underline or something.

**Comment by siovene** [comment]
PS: you should really only post one issue per report, because I need to close this after I add the logo to the app ;-)

**Comment by clagom** [comment]
Right, opening a new issue for the alignment problem
