### ISSUE TITLE
Some text is invisible when switching between views

### ISSUE THREAD

**Issue by siovene** [01org/zephyrjs-ide#40]
**Issue description**

Somehow, Chrome fails to render some `ClearSans` text when switching views. Full page reload fixes it, toggling the `font-family` attribute off and on in `body` (from the Inspector) fixes it too. The issue is not reproducible on Firefox.

**Zephyr.js IDE version:** `0.5`

**Comment by siovene** [comment]
This only appears to be an issue when serving the in-tree development build. Not an issue when building for deployment, so I'll forget about this for now.

**Comment by qiaojingx** [comment]
This issue is reproduced by http://localhost:8000/#/ with commit 7789490.
Version info missing after navigate into editor:
![selection_014](https://cloud.githubusercontent.com/assets/19813546/24441494/62724f0c-148c-11e7-9c99-45f0ca2b69a1.png)

Bottom info missing in about page after navigate into about:
![selection_013](https://cloud.githubusercontent.com/assets/19813546/24441502/67ee88c4-148c-11e7-9b5d-bc84eacedd08.png)

"Hello!" missing in home page after navigate home from about page:
![selection_012](https://cloud.githubusercontent.com/assets/19813546/24441506/6b9a79e2-148c-11e7-9703-318392c0c5d2.png)

All these can be fixed by reload page

**Comment by qiuzhong** [comment]
I recently upgraded Google Chrome from 58 to 59 for Ubuntu 16.04/Fedora 25/Windows 8.1/Windows 10, and I found this bug was totally gone.
So far I didn't encounter this bug for once with Chrome 59.

As a comparison, this bug is still reproducible 58.

* Tested Chrome versions: `58.0.3029.96, 59.0.3071.86`
* Version: `v0.16.0-alpha / 1c60c6f`

**Comment by siovene** [comment]
Yes, I suspected it was a Webkit bug anyway. Thanks for verifying!
