### ISSUE TITLE
Mobile - Responsive design

### ISSUE THREAD

**Issue by clagom** [01org/zephyrjs-ide#56]
**Issue description**
Resizing the window the design is not responsive
![screen shot 2017-02-17 at 10 50 11](https://cloud.githubusercontent.com/assets/1953388/23068396/68c34482-f51b-11e6-85a5-f118b4be3f27.png)

**Current behavior**
The layout doesn't fit to the resize of the window

**Expected behavior**
The layout should be responsive and react to the resize of the window with adjusting the UI
Example of the demo implementation visible here: http://launchbox-dev.ld.intel.com/editoride.php
![screen shot 2017-02-17 at 14 07 40](https://cloud.githubusercontent.com/assets/1953388/23068410/79354022-f51b-11e6-907e-73c3e7142e0a.png)

**Steps to reproduce**
Resizing the window

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
JS IDE FOR ZEPHYR OS / v0.8.3-alpha / df57eba

**Comment by clagom** [comment]
On mobile it looks very broken
![_tjizgtj](https://cloud.githubusercontent.com/assets/1953388/24098097/bff38156-0d60-11e7-9247-17622775b718.jpg)

**Comment by siovene** [comment]
Does it even make sense to offer the editor on a mobile device? You couldn't do any work on them because they can't connect to the IOT devices.

I propose we make sure we are responsive for all other views, for people browsing and learning about the project, but we simply display a message "the IOT IDE does not support mobile devices. Please come back using a computer", or something like that, for the editor page.
