### ISSUE TITLE
[UI]Resize windows not smoothly

### ISSUE THREAD

**Issue by qiaojingx** [01org/zephyrjs-ide#59]
**Issue description**
Resize windows not smoothly

**Current behavior**
Movement is not smoothly when try to enlarge editor window.

**Expected behavior**
Resize windows always smoothly.

**Steps to reproduce**
Resize windows by dragging the frame. Please refer to the pic.

**'JS IDE for Zephyr OS' version:** `v0.9.0-alpha / af066fe`

![screenshot from 2017-02-23 12-51-34](https://cloud.githubusercontent.com/assets/19813546/23245402/1dab7022-f9c7-11e6-9eb2-199102c0a5a1.png)

**Comment by siovene** [comment]
@qiaojingx, is this behavior also reproducible when the "OCF EXPLORER" tab is selected on the right pane, instead of the CONSOLE tab?

If so, then it's because you need a version of `ng2-split-pane` that is not installed by default by the build system because I'm waiting for [my patch  there]https://github.com/wannabegeek/ng2-split-pane/commit/3cd6459fca68720ad532c0d3c335b6cef5b2ad5a) to be released.

A temporary work around would be to build `ng2-split-pane` yourself, as follows:

```bash
git clone https://github.com/wannabegeek/ng2-split-pane.git
cd ng2-split-pane
npm install
./node_modules/.bin/tsc -p src
cd /path/to/zephyrjs-ide
npm install /path/to/ng2-split-pane
```

Once `ng2-split-pane` is released on `npm` with my patch, then this won't be necessary anymore of course.

**Comment by qiaojingx** [comment]
@siovene, this behavior is only reproducible when the "console" tab is selected.
And i can see "ng2-split-pane" folder is already there, under /zephyrjs-ide/node_modules/

**Comment by siovene** [comment]
Alright then the issue will go away when I'm able to use the upcoming update of `ng2-split-pane`. I'll put some pressure upstream for a release :-)

**Comment by qiaojingx** [comment]
Verified with JS IDE FOR ZEPHYR OS / v0.10.1-alpha / 0725450. This issue is not reproducible.
